export const members = [
  {
    id: 1,
    name: "김민영",
    role: "팀장",
    department: "MLOps",
    bgColor: "dbeafe",
    description: "END-to-END 경험이 있는 개발자입니다..",
    skills: ["MLOps", "Backend", "Azure"],
    github: "https://github.com",
    email: "minyoung@example.com",
  },
  {
    id: 2,
    name: "이서연",
    role: "팀원",
    department: "백엔드",
    bgColor: "f3e8ff",
    description: "안정적인 API 설계를 추구합니다.",
    skills: ["FastAPI", "Python", "Supabase"],
    github: "https://github.com",
    email: "seoyeon@example.com",
  },
  {
    id: 3,
    name: "박준혁",
    role: "팀원",
    department: "AI",
    bgColor: "fef3c7",
    description: "머신러닝 모델을 서비스에 연결하는 일을 합니다.",
    skills: ["Python", "TensorFlow", "ONNX"],
    github: "https://github.com",
    email: "junhyuk@example.com",
  },
  {
    id: 4,
    name: "최하은",
    role: "팀원",
    department: "디자인",
    bgColor: "fce7f3",
    description: "직관적이고 아름다운 UI를 만듭니다.",
    skills: ["Figma", "UI/UX", "Prototyping"],
    github: "https://github.com",
    email: "haeun@example.com",
  },
];
