# Generated by Django 6.0.7 on 2026-07-13 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generator', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=1000)),
                ('language', models.CharField(max_length=10)),
                ('web_master', models.EmailField(blank=True, max_length=255, null=True)),
                ('copyright', models.TextField(blank=True, null=True)),
                ('last_build_date', models.DateTimeField(blank=True, null=True)),
                ('image_title', models.CharField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('image_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=1000)),
                ('guid', models.CharField(max_length=1000, unique=True)),
                ('pub_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='news.newschannel')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
