# Generated by Django 6.0.7 on 2026-07-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newschannel_newsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('phone_number', models.CharField(max_length=20, verbose_name='전화번호')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
            ],
            options={
                'verbose_name': '샘플',
                'verbose_name_plural': '샘플',
            },
        ),
        migrations.AddField(
            model_name='newschannel',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일'),
        ),
        migrations.AddField(
            model_name='user',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일'),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
